[
  "analytics"
  "apple_tv"
  "automation"
  "backup"
  "bluetooth"
  "bthome"
  "cloud"
  "default_config"
  "google_drive"
  "group"
  "history"
  "holiday"
  "homekit"
  # Not configured, but zeroconf/BLE discovery keeps starting their config
  # flows. Without the integration present the flow cannot load, so it also
  # cannot be dismissed, and it retries forever. Installed so each discovery
  # can be ignored once in the UI.
  "homekit_controller"
  "ipp"
  "liebherr"
  "logbook"
  "matter"
  "met"
  "mobile_app"
  "playstation_network"
  "recorder"
  "remote_calendar"
  "roborock"
  "rpi_power"
  "scene"
  "script"
  "sensor"
  "shelly"
  "sun"
  "switchbot"
  "systemmonitor"
  "template"
  "thread"
  "time_date"
  "tts"
  "workday"
  "zha"
]
